name: Cypress Tests

on: [push]

jobs:
  cypress-component-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: true

      - name: Cypress Run
        uses: cypress-io/github-action@v6
        with:
          start: pnpm run dev
          component: true
